name: timetrade_wallet
description: Timetrade - Secure multi-chain crypto wallet
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.2.0
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  crypto: ^3.0.3
  bip39: ^1.0.6
  clipboard: ^0.1.3
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
